name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GHC
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.12.2'
          cabal-version: '3.12'
      - name: Cache ~/.cabal/store
        uses: actions/cache@v4
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
          restore-keys: ${{ runner.os }}-cabal-
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libgmp-dev
      - name: Build dependencies
        run: cabal build all --only-dependencies
      - name: Build project
        run: cabal build all
      - name: Run tests
        run: cabal test mcp-types
